name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "crc/frontend/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Upload frontend to Azure Storage
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name stcloudresumeauedev01 --destination '$web' --source crc/frontend --overwrite